// app/layout.tsx (Server Component)
import { Metadata } from "next";
import ReduxProvider from "./ReduxProvider";
import React, { ReactNode } from "react";
import "./globals.css";
// Define metadata for the layout
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the props type for RootLayout
interface RootLayoutProps {
  children: ReactNode;
}

// RootLayout Component
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
